name: shop_api_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.1
  modal_progress_hud_nsn: ^0.5.1
  toast: ^0.3.0
  fluttertoast: ^8.2.2
  progress_state_button: "^1.0.4"
  google_nav_bar: ^5.0.6
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.2.1
  sizer: ^2.0.15
  readmore: ^3.0.0
  shimmer: ^3.0.0
  flutter_inset_box_shadow: ^1.0.8
  like_button: ^2.0.5
  flutter_zoom_drawer: ^3.1.1
  crisp: ^0.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_slidable: ^3.1.0
  flutter_stripe: ^10.1.1
  animated_custom_dropdown: ^3.1.1
  #http: ^0.13.0
  #email_auth: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: GT-Sectra
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
